# Generated by Django 5.0.2 on 2024-03-10 14:45

import ckeditor.fields
import ckeditor_uploader.fields
import datetime
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_title', models.CharField(max_length=100, unique=True, verbose_name='عنوان برند')),
                ('brand_description', models.TextField(blank=True, null=True, verbose_name='توضیحات برند')),
                ('brand_image', models.ImageField(upload_to='products/brands/', verbose_name='لوگو')),
                ('brand_image_alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='متن جایگزین لوگو')),
                ('brand_image_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان لوگو')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='عرض تصویر')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='ارتفاع تصوبر')),
                ('css_class', models.CharField(blank=True, max_length=500, null=True, verbose_name='کلاس اضافی')),
                ('css_style', models.CharField(blank=True, max_length=1500, null=True, verbose_name='استایل اضافی')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='توضیحات متا')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='کلمات کلیدی')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('register_date', django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 10), verbose_name='تاریخ ساخت')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند ها',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_title', models.CharField(max_length=100, verbose_name='عنوان ویژگی')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'ویژگی گروه محصول',
                'verbose_name_plural': 'ویژگی های گروه محصولات',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='نام کالا')),
                ('short_description', ckeditor.fields.RichTextField(verbose_name='توضیحات مختصر کالا')),
                ('full_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات کامل کالا')),
                ('cover_picture', models.ImageField(upload_to='products/cover/', verbose_name='تصویر اصلی کالا')),
                ('group_image_alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='متن جایگزین کاور')),
                ('group_image_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان کاور')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='عرض کاور')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='ارتفاع کاور')),
                ('css_class', models.CharField(blank=True, max_length=500, null=True, verbose_name='کلاس اضافی')),
                ('css_style', models.CharField(blank=True, max_length=1500, null=True, verbose_name='استایل اضافی')),
                ('purchase_price', models.IntegerField(default=0, verbose_name='قیمت خرید')),
                ('sell_price', models.IntegerField(default=0, verbose_name='قیمت فروش')),
                ('product_discount', models.IntegerField(default=0, verbose_name='تخفیف')),
                ('product_after_discount', models.IntegerField(blank=True, default=0, null=True, verbose_name='قیمت پس از تخفیف')),
                ('slug', models.SlugField(allow_unicode=True, db_collation='utf8_persian_ci', max_length=200, unique=True, verbose_name='slug')),
                ('exist_count', models.IntegerField(default=0, verbose_name='تعداد محصول')),
                ('product_view_count', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('product_sell_count', models.IntegerField(default=0, verbose_name='تعداد فروش')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='فعال / غیر فعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف / نمایش')),
                ('register_date', django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 10), verbose_name='تاریخ درج')),
                ('updated_date', django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 10), verbose_name='تاریخ آخرین بروزرسانی')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='product.brand', verbose_name='برند کالا')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='فروشنده')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_value', models.CharField(max_length=150, verbose_name='مقدار ویژگی')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='فعال / غیر فعال')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_features', to='product.feature', verbose_name='ویژگی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_features', to='product.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی های محصولات',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(through='product.ProductFeature', to='product.feature'),
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_picture', models.ImageField(upload_to='products/galleries/', verbose_name='تصویر')),
                ('product_picture_alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='متن جایگزین تصویر')),
                ('product_picture_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان تصویر')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='عرض تصویر')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='ارتفاع تصویر')),
                ('css_class', models.CharField(blank=True, max_length=500, null=True, verbose_name='کلاس اضافی')),
                ('css_style', models.CharField(blank=True, max_length=1500, null=True, verbose_name='استایل اضافی')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='فعال / غیر فعال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_gallery', to='product.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': ' گالری محصول',
                'verbose_name_plural': 'گالری محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=100, verbose_name='عنوان گروه کالا')),
                ('group_image', models.ImageField(blank=True, null=True, upload_to='products/groups/', verbose_name='لوگو دسته بندی')),
                ('group_image_alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='متن جایگزین لوگو')),
                ('group_image_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان لوگو')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='عرض تصویر')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='ارتفاع تصوبر')),
                ('css_class', models.CharField(blank=True, max_length=500, null=True, verbose_name='کلاس اضافی')),
                ('css_style', models.CharField(blank=True, max_length=1500, null=True, verbose_name='استایل اضافی')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات گروه کالا')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='توضیحات متا')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='کلمات کلیدی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('register_date', django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 10), verbose_name='تاریخ ساخت')),
                ('slug', models.SlugField(max_length=200, verbose_name='slug')),
                ('group_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='product.productgroup', verbose_name='والد گروه کالا')),
            ],
            options={
                'verbose_name': 'گروه محصول',
                'verbose_name_plural': 'گروه محصولات',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.ManyToManyField(related_name='products_of_groups', to='product.productgroup', verbose_name='گروه کالا'),
        ),
        migrations.AddField(
            model_name='feature',
            name='product_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_features', to='product.productgroup', verbose_name='گروه کالا'),
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100, verbose_name='عنوان تگ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تگ محصول',
                'verbose_name_plural': 'تگهای محصول',
            },
        ),
    ]
