# Generated by Django 5.0.3 on 2024-03-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=11)),
                ('token', models.CharField(max_length=400)),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
    ]
