# Generated by Django 5.0.2 on 2024-03-10 14:45

import ckeditor.fields
import ckeditor_uploader.fields
import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepetitiveQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitive_question', models.CharField(blank=True, max_length=3000, null=True, verbose_name='متن سوال')),
                ('repetitive_answer', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='جواب سوال')),
                ('register_date', django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 10), verbose_name='تاریخ ساخت')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'سوال تکراری',
                'verbose_name_plural': 'سوالات تکراری',
            },
        ),
        migrations.CreateModel(
            name='SiteRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_rule_name', models.CharField(blank=True, max_length=10000, null=True, verbose_name='نام قرارداد')),
                ('site_rule_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='متن قرارداد')),
                ('register_date', django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 10), verbose_name='تاریخ ساخت')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'قانون سایت',
                'verbose_name_plural': 'قوانین سایت',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=500, verbose_name='عنوان سایت')),
                ('site_description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات سایت')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicons/', verbose_name='آیکون سایت')),
                ('co_address', models.CharField(blank=True, max_length=1500, null=True, verbose_name='آدرس پستی')),
                ('about_me', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='متن درباره ما')),
                ('tel_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره تلفن')),
                ('fax_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='فکس')),
                ('logo', models.ImageField(upload_to='logos/', verbose_name='لوگو سایت')),
                ('logo_alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='متن جایگزین لوگو')),
                ('logo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان لوگو')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='عرض لوگو')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='ارتفاع لوگو')),
                ('footer_color', models.CharField(blank=True, max_length=80, null=True, verbose_name='رنگ پانویس')),
                ('header_color', models.CharField(blank=True, max_length=80, null=True, verbose_name='رنگ سربرگ')),
                ('body_color', models.CharField(blank=True, max_length=80, null=True, verbose_name='رنگ زمینه')),
                ('register_date', django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 10), verbose_name='تاریخ ساخت')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'تنظیم اولیه',
                'verbose_name_plural': 'تنظیمات اولیه',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='نام شبکه اجتماعی')),
                ('social_media_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات شبکه اجتماعی')),
                ('social_media_url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='آدرس اینترنتی')),
                ('social_media_image', models.ImageField(blank=True, null=True, upload_to='social_media/', verbose_name='لوگو')),
                ('social_media_image_alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='متن جایگزین لوگو')),
                ('social_media_image_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان لوگو')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='عرض لوگو')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='ارتفاع لوگو')),
                ('css_class', models.CharField(blank=True, max_length=250, null=True, verbose_name='کلاس اضافی')),
                ('css_style', models.CharField(blank=True, max_length=1000, null=True, verbose_name='استایل اضافی')),
                ('register_date', django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 10), verbose_name='تاریخ ساخت')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه های اجتماعی',
            },
        ),
    ]
