# Generated by Django 5.0.3 on 2024-03-14 17:31

import ckeditor_uploader.fields
import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sitesettings_background_advantage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advantage_name', models.CharField(max_length=200)),
                ('advantage_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('register_date', django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 14))),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
            ],
            options={
                'verbose_name': 'مزیت رقابتی',
                'verbose_name_plural': 'مزیت های رقابتی',
            },
        ),
    ]
