# Generated by Django 5.0.3 on 2024-03-14 17:36

import ckeditor_uploader.fields
import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_advantages'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='advantages/icons', verbose_name='آیکون مزیت رقابتی'),
        ),
        migrations.AlterField(
            model_name='advantages',
            name='advantage_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='advantages',
            name='advantage_name',
            field=models.CharField(max_length=200, verbose_name='نام مزیت رقابتی'),
        ),
        migrations.AlterField(
            model_name='advantages',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 14), verbose_name='تاریخ ثبت'),
        ),
    ]
