# Generated by Django 5.0.3 on 2024-03-14 19:24

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_advantages_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantages',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
