# Generated by Django 5.0.3 on 2024-03-15 18:49

import ckeditor.fields
import colorfield.fields
import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_advantages_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='event_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='متن ایونت'),
        ),
        migrations.AlterField(
            model_name='advantages',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None, verbose_name='رنگ پس زمینه'),
        ),
        migrations.AlterField(
            model_name='advantages',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 15), verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='repetitivequestions',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 15), verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='siterules',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 15), verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 15), verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 15), verbose_name='تاریخ ساخت'),
        ),
    ]
