# Generated by Django 5.0.3 on 2024-03-17 07:47

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_sitesettings_event_text_alter_advantages_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantages',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 17), verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='repetitivequestions',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 17), verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='siterules',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 17), verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 17), verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 17), verbose_name='تاریخ ساخت'),
        ),
    ]
