# Generated by Django 5.0.3 on 2024-04-02 15:06

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_advantages_register_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantages',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 4, 2), verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='repetitivequestions',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 4, 2), verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='siterules',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 4, 2), verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 4, 2), verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 4, 2), verbose_name='تاریخ ساخت'),
        ),
    ]
