# Generated by Django 5.0.3 on 2024-03-17 07:47

import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customeruser_register_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='عکس پروفایل کاربری'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 17), verbose_name='تاریخ ثبت نام'),
        ),
    ]
