# Generated by Django 5.0.2 on 2024-03-11 07:35

import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentgateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerselling',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 11), verbose_name='تاریخ فاکتور'),
        ),
        migrations.AlterField(
            model_name='sellertransaction',
            name='last_amount_receivable',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='مبلغ آخرین دریافت'),
        ),
        migrations.AlterField(
            model_name='sellertransaction',
            name='mony_request',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='مبلغ درخواستی'),
        ),
    ]
