# Generated by Django 5.0.2 on 2024-03-10 14:45

import ckeditor_uploader.fields
import datetime
import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(unique=True, verbose_name='متن در آدرس slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('register_date', django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 10), verbose_name='تاریخ ساخت')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='blog/category/', verbose_name='تصویر دسته بندی')),
                ('picture_alt', models.CharField(blank=True, max_length=250, null=True, verbose_name='متن جایگزین')),
                ('picture_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان تصویر')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='عرض تصویر')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='ارتفاع تصوبر')),
            ],
            options={
                'verbose_name': 'دسته بندی مقاله',
                'verbose_name_plural': 'دسته بندی مقاله ها',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان مقاله')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='blog/article', verbose_name='تصویر مقاله')),
                ('picture_alt', models.CharField(blank=True, max_length=250, null=True, verbose_name='متن جایگزین')),
                ('picture_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان تصویر')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='عرض تصویر')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='ارتفاع تصوبر')),
                ('meta_keyword', models.CharField(blank=True, max_length=700, null=True, verbose_name='Meta Keyword')),
                ('meta_description', models.CharField(blank=True, max_length=700, null=True, verbose_name='Meta Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('register_date', django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 10), verbose_name='تاریخ ساخت')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blog.blogcategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقاله ها',
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=300, verbose_name='تگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('register_date', django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 10), verbose_name='تاریخ ساخت')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='blog.blog', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
    ]
