# Generated by Django 5.0.2 on 2024-03-10 14:45

import datetime
import django.db.models.deletion
import django_jalali.db.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_amount', models.IntegerField(blank=True, null=True, verbose_name='مقدار مالیات')),
                ('payable_amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ قابل پرداخت')),
                ('receiver_address', models.TextField(verbose_name='آدرس گیرنده')),
                ('received_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس گیرنده')),
                ('received_full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام گیرنده')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کدپستی')),
                ('invoice_description', models.TextField(blank=True, null=True, verbose_name='توضیحات فاکتور')),
                ('is_pay', models.BooleanField(default=False, verbose_name='پرداخت / عدم پرداخت')),
                ('ref_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ref Id')),
                ('authority', models.CharField(blank=True, max_length=500, null=True, verbose_name='authority')),
                ('tracking_code', models.UUIDField(default=uuid.UUID('68f4ee77-b0a1-4746-933a-6906f7fbf207'), editable=False, unique=True, verbose_name='کد پیگیری')),
                ('register_date', django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 10), verbose_name='تاریخ فاکتور')),
                ('delivery_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('is_returned', models.BooleanField(default=False, verbose_name='برگشتی')),
                ('returned_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ مرجوع')),
                ('invoice_status', models.CharField(choices=[('0', 'سبد خرید'), ('1', 'در حال پیگیری'), ('2', 'تایید شده'), ('3', 'تحویل به پست'), ('4', 'تحویل به مشتری')], default='0', max_length=200, verbose_name='وضعیت سفارش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='تعداد')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت محصول')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='invoice.invoice', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_item', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'محصول سفارش',
                'verbose_name_plural': 'محصولات سفارش',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.TextField(verbose_name='متن گزارش')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_logs', to='invoice.invoice', verbose_name='گزارش سفارش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گزارش سفارش',
                'verbose_name_plural': 'گزارشات سسفارش',
            },
        ),
    ]
