# Generated by Django 5.0.2 on 2024-03-10 15:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tracking_code',
            field=models.UUIDField(default=uuid.UUID('7a4ee248-122f-4a4d-88e9-34d77a61fea6'), editable=False, unique=True, verbose_name='کد پیگیری'),
        ),
    ]
