# Generated by Django 5.0.2 on 2024-03-11 07:35

import datetime
import django_jalali.db.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoice_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 11), verbose_name='تاریخ فاکتور'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tracking_code',
            field=models.UUIDField(default=uuid.UUID('a90193ba-ce18-4ab7-bb23-49fc86aa21c6'), editable=False, unique=True, verbose_name='کد پیگیری'),
        ),
    ]
