# Generated by Django 5.0.3 on 2024-03-12 11:01

import datetime
import django_jalali.db.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_invoice_register_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 12), verbose_name='تاریخ فاکتور'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tracking_code',
            field=models.UUIDField(default=uuid.UUID('79356376-fa02-40a3-a4cc-1a367be02fdb'), editable=False, unique=True, verbose_name='کد پیگیری'),
        ),
    ]
