# Generated by Django 5.0.3 on 2024-03-13 07:01

import datetime
import django.db.models.deletion
import django_jalali.db.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_invoice_register_date_and_more'),
        ('product', '0004_alter_brand_register_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 13), verbose_name='تاریخ فاکتور'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tracking_code',
            field=models.UUIDField(default=uuid.UUID('eed923da-a394-4e6f-9a20-14021edbe543'), editable=False, unique=True, verbose_name='کد پیگیری'),
        ),
        migrations.CreateModel(
            name='Mixed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت کل ترکیب')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mixed_item', to='invoice.invoice', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'ترکیب',
                'verbose_name_plural': 'لیست ترکیب ها',
            },
        ),
        migrations.CreateModel(
            name='MixedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='تعداد')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت ترکیب')),
                ('mix', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mix_items', to='invoice.mixed', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mix_product_item', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'محصول ترکیب',
                'verbose_name_plural': 'محصولات ترکیب',
            },
        ),
    ]
