# Generated by Django 5.0.3 on 2024-03-13 07:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_invoice_register_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tracking_code',
            field=models.UUIDField(default=uuid.UUID('221f27b1-1acc-42f0-9ff9-70864e3f8d9e'), editable=False, unique=True, verbose_name='کد پیگیری'),
        ),
        migrations.AlterField(
            model_name='mixeditem',
            name='mix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mix_items', to='invoice.mixed', verbose_name='سفارش'),
        ),
    ]
