# Generated by Django 5.0.3 on 2024-03-14 17:27

import datetime
import django_jalali.db.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_invoice_tracking_code_alter_mixeditem_mix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 14), verbose_name='تاریخ فاکتور'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tracking_code',
            field=models.UUIDField(default=uuid.UUID('bd3119d5-3258-4d22-8752-9a644865681e'), editable=False, unique=True, verbose_name='کد پیگیری'),
        ),
    ]
