# Generated by Django 5.0.3 on 2024-03-14 17:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_alter_invoice_register_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tracking_code',
            field=models.UUIDField(default=uuid.UUID('36b5f650-ba43-48a3-8890-ad22b5acb2db'), editable=False, unique=True, verbose_name='کد پیگیری'),
        ),
    ]
