# Generated by Django 5.0.3 on 2024-03-14 17:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_alter_invoice_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tracking_code',
            field=models.UUIDField(default=uuid.UUID('7a54c268-fa42-4d71-85f6-b769798755f5'), editable=False, unique=True, verbose_name='کد پیگیری'),
        ),
    ]
