# Generated by Django 5.0.3 on 2024-03-14 19:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_alter_invoice_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tracking_code',
            field=models.UUIDField(default=uuid.UUID('3348b807-9263-490b-8d37-4ee0d2318890'), editable=False, unique=True, verbose_name='کد پیگیری'),
        ),
    ]
