# Generated by Django 5.0.3 on 2024-03-15 18:49

import datetime
import django_jalali.db.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_alter_invoice_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 3, 15), verbose_name='تاریخ فاکتور'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tracking_code',
            field=models.UUIDField(default=uuid.UUID('5e7ed79e-0d83-4534-8d97-426f2a2fa2bd'), editable=False, unique=True, verbose_name='کد پیگیری'),
        ),
    ]
