# Generated by Django 5.0.3 on 2024-04-02 15:06

import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_alter_invoice_register_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 4, 2), verbose_name='تاریخ فاکتور'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tracking_code',
            field=models.CharField(default='7905000', editable=False, max_length=7, unique=True, verbose_name='کد پیگیری'),
        ),
    ]
