# Generated by Django 5.0.3 on 2024-04-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_alter_invoice_register_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tracking_code',
            field=models.CharField(default='6128330', max_length=8, unique=True, verbose_name='کد پیگیری'),
        ),
    ]
