# Generated by Django 5.0.3 on 2024-04-08 15:03

import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_alter_invoice_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='register_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 4, 8), verbose_name='تاریخ فاکتور'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tracking_code',
            field=models.CharField(default='5994125', max_length=8, unique=True, verbose_name='کد پیگیری'),
        ),
    ]
